import React, { useState } from "react";
import Head from "next/head";
import { Inter } from "next/font/google";
import dayjs from "dayjs";

import TimePicker from "@/components/TimePicker";

import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [dateTime, setDateTime] = useState(() => dayjs().format());
  const [userHasSelectedTime, setUserHasSelectedTime] = useState(false);

  const handleTimeChange = (updatedDateTime) => {
    setDateTime(updatedDateTime);

    if (!userHasSelectedTime) {
      setUserHasSelectedTime(true);
    }
  };

  return (
    <>
      <Head>
        <title>React Time Picker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h1 className={styles.heading}>
          Selected time:{" "}
          {userHasSelectedTime ? dayjs(dateTime).format("HH:mm") : ""}
        </h1>

        <TimePicker
          className={styles.picker}
          dateTime={dateTime}
          onChange={handleTimeChange}
        />
      </main>
    </>
  );
}
